### ISSUE TITLE
Not working in rc1

### ISSUE THREAD

**Issue by MurhafSousli** [cwadrupldijjit/ng2-parallax#2]
Hi .. is there any plans for an update, it's not working with the latest rc1, thank you

**Comment by cwadrupldijjit** [comment]
It's in my plans. I haven't spent a lot of time on it lately due to my busy
schedule and working late in efforts of shipping my business's product.

Have you continued to work in webpack?  It's likely I'll extend the
functionality to webpack once I've gotten it all working with the @angular
release candidate.

**Comment by MurhafSousli** [comment]
yea still working with webpack, that's cool, the rc2 is coming next week as I heard.

**Comment by warapitiya** [comment]
Not working for RC4. Hope you'll have a solution for this ASAP. 

FYI: Using System.js

**Comment by cwadrupldijjit** [comment]
The reasons why the plugin isn't working in >= rc1 is because of the
package scheme changing in rc1. I'm working on it, though having to put it
on the back burner a bit because this if the week before my company ships
its product.

I'm working on updating this bit by bit, though I don't anticipate it
taking too much.

**Comment by oktav777** [comment]
@cwadrupldijjit still no ETA? Thinking already on writing my own parallax directive ...

**Comment by oktav777** [comment]
Only imports seems to be broken, the logic is ok!

I copied `parallax.directive.ts` to my project fixed the imports and it works.

``` typescript
import { Directive, ElementRef, Host, Input, Optional, OnInit } from 'angular2/core'
                                                                             ^
```

to

``` typescript
import { Directive, ElementRef, Host, Input, Optional, OnInit } from '@angular/core'
                                                                      ^
```

I wanted to make pull request, tried to compile, but the build process seems to be broken, too many dependencies changed since then.

**Comment by cwadrupldijjit** [comment]
I'll fix that today and get back with you on it.

I'm still trying to get the new NgModules to work with it. Best case,
that's figured out today and modules will work. Worst case, I ignore the
modules and you just install the directive.
