### ISSUE TITLE
Wrong config params on the documentation (Readme.md)

### ISSUE THREAD

**Issue by jmandreslopez** [cwadrupldijjit/ng2-parallax#7]
I just spend a while trying to make this library to work until I checked the actual directive and noticed that the config params are different from the ones on the documentation. I.E. the 'parallaxInitVal' is renamed to 'initialValue'. Could you change that for future references?

**Comment by cwadrupldijjit** [comment]
Thanks for catching that!

I have spent some time updating everything, since the version of Angular has changed drastically since the last time I had worked on this project.  It has been since updated, and I released a major version because of the API update.

I will be pushing up changes to the readme shortly, and will be working on the documentation on my website when I can--it's currently undergoing the same, maybe larger upgrade to the current version of Angular, but the documentation should be corrected within the next several weeks.

In the meantime, if your IDE/code editor supports IntelliSense or an equivalent, then the importable `ParallaxConfig` should be able to let you know what you can use.  And, of course, taking a look at the actual source/non-minified file is also a great way of doing that.  I'm working on updating the comments in there or the associated `.d.ts` files to jsDocs so that can be used as well.

**Comment by cwadrupldijjit** [comment]
And, as a note, if you would like to contribute to the documentation, you can possibly do that by checking [my webpage repo](https://github.com/cwadrupldijjit/cwadrulpdijjit.github.io) in the `app/subpages/ng2-parallax/ts-examples` folder.  Understand that if you do this, however, I may not accept your PR, but still copy your changes over to the documentation, as the architecture of the website will be changing to fit better practices.

The documentation there won't be changing until after a couple of weeks, as I'm actually getting married in the morning and will be gone for a week afterward.  I may be available to check PRs, but no active modification of this project will be happening in that time.

**Comment by cwadrupldijjit** [comment]
I have fixed all of the issues I could find with the README, but I did that when I upgraded the component to work with the latest version of Angular.  Let me know if any problems still exist by adding an issue to the new repo:
[cwdj-parallax](https://github.com/cwadrupldijjit/cwdj-parallax)
